server:
  port: 8892
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud_db?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  application:
    name: cloud-producer # 应用名称，会在Eureka中显示
eureka:
  client:
    service-url: # EurekaServer的地址
      defaultZone: http://127.0.0.1:8083/eureka/
mybatis:
  type-aliases-package: com.xiao.pojo

